version: "3"

services:
  v2ray:
    image: v2ray/official
    volumes:
      - ./config.json:/etc/v2ray/config.json
    expose:
      - "8002"

  caddy:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile:ro
      - ./caddyCertificates:/root/.caddy
    environment:
      - ACME_AGREE=true
    ports:
      - "80:80"
      - "443:443"
