version: '3'

services:
  v2ray:
    image: v2ray/official
    volumes:
    - ./config.json:/etc/v2ray/config.json
    expose:
    - "8002" # if you need to change this you should change Caddyfile as well

  caddy:
    image: abiosoft/caddy
    volumes:
    - ./Caddyfile:/etc/Caddyfile:ro
    - ./caddyCertificates:/root/.caddy
    environment:
    - ACME_AGREE=true
    ports:
    - "80:80"
    - "443:443"